name: "Push to actions"
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  push_actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout curse-locale-action
        uses: actions/checkout@v4
        with:
          repository: curse-action/locale
          path: actions/locale
          token: ${{ secrets.PAT }}

      - name: Checkout curse-publish-action
        uses: actions/checkout@v4
        with:
          repository: curse-action/publish
          path: actions/publish
          token: ${{ secrets.PAT }}

      - name: Checkout curse-update-action
        uses: actions/checkout@v4
        with:
          repository: curse-action/update
          path: actions/update
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: npm install
        run: npm install

      - name: Build actions
        run: npm run action

      - name: Commit curse-locale-action
        uses: EndBug/add-and-commit@v9
        with:
          cwd: actions/locale
          message: "auto build"

      - name: Commit curse-publish-action
        uses: EndBug/add-and-commit@v9
        with:
          cwd: actions/publish
          message: "auto build"

      - name: Commit curse-update-action
        uses: EndBug/add-and-commit@v9
        with:
          cwd: actions/update
          message: "auto build"

